services:

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - ha_network

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - ./ha_config/:/config/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # privileged: true
    networks:
      - ha_network
      
networks:
  ha_network:
    driver: bridge
